# Base de Datos Oracle
db.url=jdbc:oracle:thin:@desarrolloacademico_medium?TNS_ADMIN=C:/Users/Usuario/Desktop/tareas/cuatri3/proyecto integrador/Desarrollo-Academico/src/main/resources/wallet
db.user=ADMIN
db.password=Desarrolloacademico123

# Correo Gmail
mail.user=20253ds088@utez.edu.mx
mail.password=kgbrqbdftovxbppb
